p:use`$"fusion:",string M;
v:"F"$5#p.version[]
t)([x0:enlist("bar";3;6)])~p.match["bar";"foobar";::]
t)([x0:(("foo";0;3);("bar";3;6));xx:enlist("foo";0;3);x2:enlist("bar";3;6)])~p.match["(?<xx>foo)|(bar)";"foobar";::]
t)([x0:(("foo";0;3);("bar";3;6));x1:enlist("ar";4;6)])~p.match["foo|b(ar)";"foobar";::]
t)((enlist `x0)!enlist ())~p.match["foo";"Foo";::]
t)([x0:()])~p.match["foo";"Foo";::]
t)([x0:()])~p.match["foo";"Foo";`]
t)([x0:enlist("Foo";0;3)])~p.match["foo";"Foo";`caseless]
t)([x0:enlist("Foo";0;3)])~p.match["foo";"Foo";enlist`caseless]
t)$[v>=10.47;([x0:(("";0;0);("";1;1);("";2;2))]);([x0:()])]~p.match["f*";"bar";::]
t)([x0:()])~p.match["f*";"bar";`notempty]
t)((enlist `x0)!enlist ())~p.match["^foo";"\nfoo";::]
t)([x0:()])~p.match["^foo";"\nfoo";::]
t)([x0:enlist("foo";1;4)])~p.match["^foo";"\nfoo";`multiline]
t)([x0:enlist("Foo";1;4)])~p.match["^foo";"\nFoo";`multiline`caseless]
t)(`x0`x`x!(enlist("foobar";0;6);enlist("foo";0;3);enlist("bar";3;6)))~p.match["(?<x>foo)(?<x>bar)";"foobar";`dupnames]
t)"pcre2: compile at 4: missing closing parenthesis"~.[p.match;("(foo";"foo";::);::]
t)$[v<=10.23;1b;"pcre2: match: nested recursion at the same subject position"~.[p.match;("(a(?1)z||(?1)++)$";"abcd";::);::]]
t)"foobazfoobaz"~p.replace["bar";"foobarfoobar";"baz";::]
t)"foobar"~p.replace["Bar";"foobar";"baz";::]
t)"foobaz"~p.replace["Bar";"foobar";"baz";`caseless]
t)112h~type p.compile["foo";::]
t)r:p.compile["bar";::];([x0:enlist("bar";3;6)])~p.match[r;"foobar";::]
t)"foobazfoobaz"~p.replace[r;"foobarfoobar";"baz";::]
t)"foobazfoobaz"~p.replace[p.compile["bar";::];"foobarfoobar";"baz";::]
t)([x0:enlist("Foo";0;3)])~p.match[p.compile["foo";`caseless];"Foo";::]
t)([x0:((enlist"\300";0;1);(enlist"\257";1;2))])~p.match[".?";"\300\257";::]
t)"pcre2: match: UTF-8 error: overlong 2-byte sequence"~.[p.match;("(*UTF).?";"\300\257";::);::]
t)"pcre2: match: UTF-8 error: overlong 2-byte sequence"~.[p.match;(".?";"\300\257";`utf);::]
t)"pcre2: compile at 6: UTF-8 error: overlong 2-byte sequence"~.[p.compile;("(*UTF)\300\257";::);::]
t)"pcre2: compile at 0: UTF-8 error: overlong 2-byte sequence"~.[p.compile;("\300\257";`utf);::]
t)([x0:()])~p.match[enlist".";enlist"\n";::]
t)([x0:enlist(enlist"\n";0;1)])~p.match[enlist".";enlist"\n";`dotall]